version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: broccoli-asset-rev
    versions:
    - "> 2.6.0"
  - dependency-name: ember-cli-eslint
    versions:
    - "> 4.2.3"
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.2
    - 3.25.3
  - dependency-name: "@glimmer/syntax"
    versions:
    - 0.73.2
    - 0.74.0
    - 0.74.2
    - 0.75.0
    - 0.77.1
    - 0.77.3
    - 0.77.6
  - dependency-name: ember-source
    versions:
    - 3.25.1
    - 3.25.3
